# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Burmese spellchecker"
my = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Burmese, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
my = "TRANSLATE: A spellchecker for Burmese, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.my"

[windows]
system_product_code = "{F99EE44A-8005-4D1A-AFD1-A6EDEB79FFBD}_is1"

[package.speller]
name = "Burmese"
version = "0.1.0"

[package.grammar]
name = "Burmese"
version = "0.1.0"

[package.tts-text-proc]
name = "Burmese"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
