template = ""
rev_id = 92
template_sha = "b87d1b5a59a119a47b497f01ac9409ebecf95eb4"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
