template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "nucl1310"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
