template = "https://github.com/giellalt/template-lang-und"
rev_id = 269
template_sha = "c43b39fe5507de4cc3a96e60743ab44578e61fd2"

[replacements]
__GLOTTOLOG_ID__ = "nucl1310"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
