template = ""
rev_id = 196
template_sha = "90dec2979df9debc902fd56f04add3e9e5458b29"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
