template = ""
rev_id = 180
template_sha = "2f2647872aeaeeb6fcd11578033d8bbae6133b84"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
